config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('', views.index, name='index'),
    path('business/', views.business, name='business'),
    path('entertainment/', views.enter, name='enter'),
    path('health/', views.health, name='health'),
    path('science/', views.science, name='science'),
    path('sports/', views.sports, name='sports'),
    path('tech/', views.tech, name='tech'),
]

news/models.py
from django.db import models

# Create your models here.

news/views.py
from django.shortcuts import render
from newsapi import NewsApiClient


def index(request):
    newsapi = NewsApiClient(api_key='ea639b3b11674569a687199bf9bc1b19')
    news_headlines = newsapi.get_top_headlines(country='kr')

    data = news_headlines['articles']
    title = []
    desc = []
    url = []
    img = []
    pub = []

    for i in range(len(data)):
        f = data[i]
        title.append(f['title'])
        desc.append(f['description'])
        url.append(f['url'])
        img.append(f['urlToImage'])
        pub.append(f['publishedAt'])

    news_list = zip(title, desc, url, img, pub)
    context = {'news_list': news_list}

    return render(request, 'news/index.html', context)


def business(request):
    newsapi = NewsApiClient(api_key='ea639b3b11674569a687199bf9bc1b19')
    news_headlines = newsapi.get_top_headlines(country='kr', category='business')

    data = news_headlines['articles']
    title = []
    desc = []
    url = []
    img = []
    pub = []

    for i in range(len(data)):
        f = data[i]
        title.append(f['title'])
        desc.append(f['description'])
        url.append(f['url'])
        img.append(f['urlToImage'])
        pub.append(f['publishedAt'])

    news_list = zip(title, desc, url, img, pub)
    context = {'news_list': news_list}

    return render(request, 'news/business.html', context)


def enter(request):
    newsapi = NewsApiClient(api_key='ea639b3b11674569a687199bf9bc1b19')
    news_headlines = newsapi.get_top_headlines(country='kr', category='entertainment')

    data = news_headlines['articles']
    title = []
    desc = []
    url = []
    img = []
    pub = []

    for i in range(len(data)):
        f = data[i]
        title.append(f['title'])
        desc.append(f['description'])
        url.append(f['url'])
        img.append(f['urlToImage'])
        pub.append(f['publishedAt'])

    enterNews_list = zip(title, desc, url, img, pub)
    context = {'enterNews_list': enterNews_list}

    return render(request, 'news/enter.html', context)


def health(request):
    newsapi = NewsApiClient(api_key='ea639b3b11674569a687199bf9bc1b19')
    news_headlines = newsapi.get_top_headlines(country='kr', category='health')

    data = news_headlines['articles']
    title = []
    desc = []
    url = []
    img = []
    pub = []

    for i in range(len(data)):
        f = data[i]
        title.append(f['title'])
        desc.append(f['description'])
        url.append(f['url'])
        img.append(f['urlToImage'])
        pub.append(f['publishedAt'])

    news_list = zip(title, desc, url, img, pub)
    context = {'news_list': news_list}

    return render(request, 'news/health.html', context)


def science(request):
    newsapi = NewsApiClient(api_key='ea639b3b11674569a687199bf9bc1b19')
    news_headlines = newsapi.get_top_headlines(country='kr', category='science')

    data = news_headlines['articles']
    title = []
    desc = []
    url = []
    img = []
    pub = []

    for i in range(len(data)):
        f = data[i]
        title.append(f['title'])
        desc.append(f['description'])
        url.append(f['url'])
        img.append(f['urlToImage'])
        pub.append(f['publishedAt'])

    news_list = zip(title, desc, url, img, pub)
    context = {'news_list': news_list}

    return render(request, 'news/science.html', context)


def sports(request):
    newsapi = NewsApiClient(api_key='ea639b3b11674569a687199bf9bc1b19')
    news_headlines = newsapi.get_top_headlines(country='kr', category='sports')

    data = news_headlines['articles']
    title = []
    desc = []
    url = []
    img = []
    pub = []

    for i in range(len(data)):
        f = data[i]
        title.append(f['title'])
        desc.append(f['description'])
        url.append(f['url'])
        img.append(f['urlToImage'])
        pub.append(f['publishedAt'])

    news_list = zip(title, desc, url, img, pub)
    context = {'news_list': news_list}

    return render(request, 'news/sports.html', context)


def tech(request):
    newsapi = NewsApiClient(api_key='ea639b3b11674569a687199bf9bc1b19')
    news_headlines = newsapi.get_top_headlines(country='kr', category='technology')

    data = news_headlines['articles']
    title = []
    desc = []
    url = []
    img = []
    pub = []

    for i in range(len(data)):
        f = data[i]
        title.append(f['title'])
        desc.append(f['description'])
        url.append(f['url'])
        img.append(f['urlToImage'])
        pub.append(f['publishedAt'])

    news_list = zip(title, desc, url, img, pub)
    context = {'news_list': news_list}

    return render(request, 'news/tech.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>뉴스앱</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/moonspam/NanumSquare@1.0/nanumsquare.css">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css2?family=Roboto:wght@900&display=swap">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
</head>
<body>
    <div id="wrap">
        <header class="header">
            <div class="top_menu">
                <h1 class="logo"><a href="{% url 'news:index' %}">news</a></h1>
                <div class="mBtn">
                    <a href="#!">button</a>
                </div>
            </div>
            <nav id="nav" class="swiper-container">
                <ul class="swiper-wrapper">
                    <li class="swiper-slide tab"><a href="{% url 'news:business' %}">비지니스</a></li>
                    <li class="swiper-slide tab"><a href="{% url 'news:enter' %}">엔터테인먼트</a></li>
                    <li class="swiper-slide tab"><a href="{% url 'news:health' %}">건강/헬스</a></li>
                    <li class="swiper-slide tab"><a href="{% url 'news:science' %}">과학</a></li>
                    <li class="swiper-slide tab"><a href="{% url 'news:sports' %}">스포츠</a></li>
                    <li class="swiper-slide tab"><a href="{% url 'news:tech' %}">IT/테크</a></li>
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock %}
    </div>
    {% load static %}
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script>
        <!-- Initialize Swiper -->
        const swiper = new Swiper('.swiper-container', {
            slidesPerView: 4,
            spaceBetween: 15,
            pagination: {
                el: '.swiper-pagination',
                clickable: true,
            },
        });
    </script>
</body>
</html>

templates/news/business.html
{% extends 'base.html' %}
{% block content %}
<section class="business">
    <div class="news">
        <ul>
            {% for title, desc, url, img, pub in news_list %}
            <li>
                <div class="item">
                    <a href="{{ url }}">
                        <img src="{{ img }}" alt="">
                        <h4>{{ title }}</h4>
                    </a>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock %}

templates/news/enter.html
{% extends 'base.html' %}
{% block content %}
<section class="enter">
    <div class="news">
        <ul>
            {% for title, desc, url, img, pub in enterNews_list %}
            <li>
                <div class="item">
                    <a href="{{ url }}">
                        <img src="{{ img }}" alt="">
                        <h4>{{ title }}</h4>
                    </a>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock %}

templates/news/health.html
{% extends 'base.html' %}
{% block content %}
<section class="health">
    <div class="news">
        <ul>
            {% for title, desc, url, img, pub in news_list %}
            <li>
                <div class="item">
                    <a href="{{ url }}">
                        <img src="{{ img }}" alt="">
                        <h4>{{ title }}</h4>
                    </a>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock %}

templates/news/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="news">
        <ul>
            {% for title, desc, url, img, pub in news_list %}
            <li>
                <div class="item">
                    <a href="{{ url }}">
                        <img src="{{ img }}" alt="">
                        <h4>{{ title }}</h4>
                    </a>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/news/science.html
{% extends 'base.html' %}
{% block content %}
<section class="science">
    <div class="news">
        <ul>
            {% for title, desc, url, img, pub in news_list %}
            <li>
                <div class="item">
                    <a href="{{ url }}">
                        <img src="{{ img }}" alt="">
                        <h4>{{ title }}</h4>
                    </a>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock %}

templates/news/sports.html
{% extends 'base.html' %}
{% block content %}
<section class="sports">
    <div class="news">
        <ul>
            {% for title, desc, url, img, pub in news_list %}
            <li>
                <div class="item">
                    <a href="{{ url }}">
                        <img src="{{ img }}" alt="">
                        <h4>{{ title }}</h4>
                    </a>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock %}

templates/news/tech.html
{% extends 'base.html' %}
{% block content %}
<section class="tech">
    <div class="news">
        <ul>
            {% for title, desc, url, img, pub in news_list %}
            <li>
                <div class="item">
                    <a href="{{ url }}">
                        <img src="{{ img }}" alt="">
                        <h4>{{ title }}</h4>
                    </a>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock %}